name: Deploy Django to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/celebrity-frontend
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo lsof -t -i:8000 | xargs kill -9 || true
            nohup python manage.py runserver 0.0.0.0:8000 > log.txt 2>&1 &